# ============================================================
# RC01 - ms-auth | Puerto 8081
# Microservicio de autenticación y usuarios
# ============================================================
server.port=8081
spring.application.name=ms-auth

# Supabase - PostgreSQL
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.deqpchznhvhesicjyyqo
spring.datasource.password=YUfwXSa09IXa4ef5
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.datasource.hikari.connection-init-sql=SET search_path TO public

spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1

